### ISSUE TITLE
Specs don't run unless shards are installed on host

### ISSUE THREAD

**Issue by KimBurgess** [PlaceOS/drivers#12]
Due to `lib/` being mapped in as a volume, specs will not run until `shards install` has been run on the host.

To simplify initial spinup it may be worth mapping these in to an alternative path and appending this to the `CRYSTAL_PATH` env var.

This may cause some issues with handling different shard versions / introduce fragility where specs run locally, but not on other environments. Needs some further thought & discussion before implementation.

**Comment by caspiano** [comment]
We could
- Put a `shards check || shards install` in the entrypoint 
- Create a small script that just runs `shards check || shards install` before `docker-compose up -d`. Usage: `./start-harness`

**Comment by KimBurgess** [comment]
The crystal compiler [supports the `CRYSTAL_PATH` env var](https://github.com/crystal-lang/crystal/blob/c41640fc205840a544f23eda33a6fedb4a184088/src/compiler/crystal/crystal_path.cr#L17).

It should be possible to mount lib from the host to an alternative path, than have both that path and `lib` assigned there. This was if host is empty (`shards install` hasn't been run) it will fallback to the shards backed into the container.
