### ISSUE TITLE
Lenel/OpenAccess > create(Badge): Following a Lenel API error response, created Badges will have incorrect activate/deactivate Times

### ISSUE THREAD

**Issue by w-le** [PlaceOS/drivers#144]
**Describe the bug**

When using create_badge() with `activate` and `deactivate` timestamps that are within the current day, the resulting Lenel Badge (when looked up) will be valid but with activate/deactivate in the distant future.
Example resulting Badge:
```
    {
        "badgekey": 28146,
        "activate": "2383-05-17T10:05:59+04:00",
        "deactivate": "2383-05-17T13:05:59+04:00",
        "id": 50009,
        "personid": 23721,
        "status": 1,
        "type": 10
    }
```

It appears to only start happening AFTER a previous create_badge() is called that resulted in an error response from Lenel, such as:
```
Lenel::OpenAccess (mod-GzZZgxKr~kn)
The person already has the maximum number of active badges. 
```
After that, ALL subsequent create_badge() calls will result in an Badges with defective `activate` and `deactivate` properties, until the DRIVER is restarted (e.g. by updating it).

The activate&deactivate timestamps will increase (by a few hundred years) each time there is another Lenel API error response.

**To Reproduce**

On an instance of PlaceOS that has the Lenel Openaccess Module running and integrated:
1. Use `create_badge()` , but induce an error response from the API by either assigning more total badges than allowed to a single user (e.g. 3 for our test client), or attempting to assign a badge ID that already exists.
2. Now, make a separate `create_badge()` call with valid properties including `activate` and `deactivate` timestamps
3. Lookup the Badge that was succesfully created, note that activate and deactivate properties are in the distant future, instant of matching the inputted Times.

Am very happy to do a screenshare to demo the issue in an integrated staging environment.

** Expected Behaviour **
Lenel API error responses should have no impact on subsequent objects that are created. It should be safe to make an erroneous API request, handle the error and then make an appropriate follow-up request.

** More Information **
The issue was first noticed while an associated visitor qr workflow was fully integrated (a neighboring Logic driver was calling Security_1.create_badge). While debug logs suggested that valid `Time` arguments were being passed to Security_1, I wanted to be 100% sure that my Logic wasn't the cause so I removed all other components and isolate the issue. 

I added a [create_badge_epoch()](https://github.com/w-le/drivers/blob/master/drivers/lenel/open_access.cr#L146-L153) method to debug fork of the Lenel driver so that badges can be created directly within backoffice. Also tried adding very verbose debugging at the method and lower levels but wasn't able to get the raw text that was being Posted to the Lenel API (just due to lack of Crystal skills).

**Comment by kimburgess** [comment]
That is utterly surreal - beautiful debugging though!

If you'd like to add some more verbose inspection of outgoing messages, [pop this back in](https://github.com/w-le/drivers/blob/5786f73a425f07a8c09b2ea361de36f070500a69/drivers/lenel/open_access.cr#L23-L25). It would be interesting to isolate this to something happening here, or potentially an issue on the Lenel API. Hopefully that addition should assist with this.

**Comment by w-le** [comment]
perfect thanks! exactly what I was looking for.  Will test today

**Comment by w-le** [comment]
Inspection of the Post Body confirms that it's a Lenel API issue.

A reliable workaround appears to be to convert the `activate` and `deactivate` ISO 8601 time strings to the Lenel server's timezone. This can be done in the function or external Logic driver that's calling this driver's `create_badge()`.

A Lenel service provider has been notified of the technical details of the issue.
