### ISSUE TITLE
Bug: hidden files/directories

### ISSUE THREAD

**Issue by caspiano** [PlaceOS/drivers#15]
Hidden files displayed in repository listing of the Spec Runner.

![Screen Shot 2020-06-17 at 13 39 31](https://user-images.githubusercontent.com/18466497/84852642-b835a200-b0a0-11ea-8bdf-d432b204054f.jpg)

**Comment by jeremyw24** [comment]
@MrYuion is this fixed?

**Comment by MrYuion** [comment]
Hmm... No, I can fix that but it might be better for the backend to not return it.

**Comment by stakach** [comment]
@MrYuion needs a bit of an update anyway, branding is ACA and still says `aca_drivers`
I can filter out anything starting with a `.`

**Comment by MrYuion** [comment]
Yeah. I was possibly thinking of giving it an overhaul.

**Comment by MrYuion** [comment]
I've fixed this one the frontend with my refactor.
https://github.com/PlaceOS/driver-spec-runner
