### ISSUE TITLE
Floorsense Driver: switch to websocket protocol

### ISSUE THREAD

**Issue by w-le** [PlaceOS/drivers#169]
Floorsense have shared an example js demonstrating the ws protocol. It can be found in gdrive under [product/external services/sensors/floorsense](https://drive.google.com/drive/u/1/folders/1Jzq2y59yfsTFi4-OEO8KyXbzXqKjhbm2).

Owners have stated that ws protocol has the exact same endpoints and params as the REST API.
ws uri is `wss://<REDACTED>-uat.floorsense.com.au/ws`

**Comment by caspiano** [comment]
Closed out by be293f235e9972a0e31a50e2248f1df1a6758d35
