### ISSUE TITLE
Test harness UI truncates output

### ISSUE THREAD

**Issue by KimBurgess** [PlaceOS/drivers#17]
When running a spec that fails due to a compilation error the UI truncates the tailing 3 lines of output.

Inspecting the requests shows the full output being returned from the `/test` endpoint, which points to this being potentially UI related.

As an example, a test run may end in:
```
There was a problem expanding macro 'macro_139728512985392'
Called macro defined in macro 'args'
 2 | {% if true %}
Which expanded to:
    1 | 
    2 |     {
    3 |       
    4 |         a: a
    5 |       
 >  6 |         b: b
    7 |       
    8 |     }
    9 |     
Error: expecting token '}', not 'b'
```

This then renders as:
```
There was a problem expanding macro 'macro_139728512985392'

Called macro defined in macro 'args'

 2 | {% if true %}

Which expanded to:

    1 | 
    2 |     {
    3 |       
    4 |         a: a
    5 |       
 >  6 |         b: b
    7 |   
```

**Comment by jeremyw24** [comment]
@MrYuion  whats the status here?

**Comment by MrYuion** [comment]
This should be fixed in the latest build.
Let me know if this is still an issue.
