### ISSUE TITLE
Signal router

### ISSUE THREAD

**Issue by kimburgess** [PlaceOS/drivers#172]
**Driver Type**

Logic

**Describe any desired functionality**

Provide abstractions for managing signal distribution between a set of inputs and set of outputs. The driver should provide an interface that lets you route from an input to an output across an arbitrary signal network. Any intermediate device interactions are handled internally.

**Additional context**

Previous implementation: https://github.com/acaprojects/ruby-engine-drivers/blob/beta/modules/aca/router.rb.

Internals will form the basis of room logic and should be extensible for this.

**Comment by kimburgess** [comment]
Dup of #95

**Comment by kimburgess** [comment]
@jeremyw24 any reason for the re-open?

**Comment by jeremyw24** [comment]
@kimburgess yeah just aligned it with your PR which is still open for tracking.

**Comment by kimburgess** [comment]
This ones a dup (see above) so can nuke one.
