### ISSUE TITLE
mulesoft/bookings-api driver compiles in test harness but not in core

### ISSUE THREAD

**Issue by w-le** [PlaceOS/drivers#177]
This driver written by redant used to compile just fine, but when trying to compile in core last weekend I hit this error which I've never seen before (no recent signifcant changes to the driver which should cause this)

https://github.com/PlaceOS/drivers/blob/2171f5532bda7cba493b4b5d1878f5179243d041/drivers/mulesoft/booking_api.cr#L123
```
...

   401 |             "query_bookings" => {
   402 |               
   403 |                 "venue_code" => PlaceOS::Driver::Settings.introspect(String).
   404 |                   
   405 |                     merge({ title: "String" }),
   406 |                   
   407 |               
   408 |                 "starts_at" => PlaceOS::Driver::Settings.introspect(Time).
   409 |                   
 > 410 |                     merge({ title: "Time", default: Time.local.at_beginning_of_day }),
   411 |                   
   412 |               
   413 |                 "ends_at" => PlaceOS::Driver::Settings.introspect(Time).
   414 |                   
   415 |                     merge({ title: "Time", default: Time.local.at_end_of_day }),
   416 |                   
   417 |               
   418 |             },

...

Error: no overload matches 'Hash(String, String)#merge' with type NamedTuple(title: String, default: Time)

Overloads are:
 - Hash(K, V)#merge(other : Hash(L, W))
 - Hash(K, V)#merge(other : Hash(L, W), &block)
 (PlaceOS::Resource::ProcessingError)
  from /usr/share/crystal/src/gc/boehm.cr:110:5 in 'process_resource'
  from lib/placeos-resource/src/placeos-resource.cr:169:10 in '_process_event'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from ???
  ```

Any tips on what change is required to this driver in order to get it compiling inside core again?
Note that test-harness compiles the driver and runs the spec just fine.

I've noticed that if I manually checkout placeos/drivers to a commit prior to https://github.com/place-labs/resource/commit/0921b064171a8ca453edc93e0e8bfd632e767709 and `shards install --ignore-crystal-version` then the driver will compile OK inside core.

**Comment by pkheav** [comment]
I think the issue is with the `starts_at` and `ends_at` being of type `Time` which is not a valid JSON type. I think it would work if they are changed from `Time` to `Int64` epochs and then converting those into Time objects like `start_time = Time.unix(starts_at)`

**Comment by w-le** [comment]
Thanks Phil,
Yeah that did cross my mind, but then I recalled other drivers like Lenel which had methods with `Time` params. Lenel still compiles fine inside core too, unlike this mulesoft api driver.
https://github.com/PlaceOS/drivers/blob/master/drivers/lenel/open_access.cr#L116-L123

It's just so weird that this driver compiled inside core just fine up until a couple weeks ago. And the fact that it still passes test harness compilation and tests too.

**Comment by stakach** [comment]
just bumped drivers version, think this was the fix:
https://github.com/PlaceOS/driver/commit/c14169b52f49b6f5a7433e8a0ef6864ec5a24f70

So a repo update will resolve the issue
I'll keep an eye on the Drivers report for future updates (in the actions tab)
<img width="556" alt="image" src="https://user-images.githubusercontent.com/368013/121278181-70450600-c915-11eb-9a5b-8c1f281474c7.png">

it shows which drivers are not working.
The reason it worked in the test harness is that uses its internal lib folder so was probably running an older version

**Comment by caspiano** [comment]
Here's the direct line @stakach is referencing https://github.com/PlaceOS/drivers/runs/2771931929#step:6:55

Note: it would be good to have the output of compilation failures in the report

**Comment by caspiano** [comment]
@w-le resolution confirmed https://github.com/PlaceOS/drivers/runs/2779481573#step:6:55
