### ISSUE TITLE
Bug: Module based on a driver from an older fork of drivers no longer shows available methods

### ISSUE THREAD

**Issue by pkheav** [PlaceOS/drivers#178]
**To Reproduce**

1. Add a driver from an older fork like https://github.com/pkheav/drivers/blob/c56e3e7c5409808498e052163116f4fd8fe5ff30/drivers/cisco/ise/guests.cr
2. Attempt to see available methods in backoffice like here for `Guests 2` https://placeos-dev.aca.im/backoffice/#/systems/sys-GAg-Vlc~-LM/modules

**Expected behaviour**

Should still work as per previous behaviour and show available methods so they can be executed in backoffice.

**Screenshots or a paste of terminal output**

![image](https://user-images.githubusercontent.com/18463731/121180457-cacc5c80-c858-11eb-8d7f-9045d8129eb9.png)

**Versions (please complete the following information):**

https://github.com/pkheav/drivers/tree/c56e3e7c5409808498e052163116f4fd8fe5ff30
`placeos/core:placeos-1.2105.3`
`placeos/rest-api:placeos-1.2105.3`

**Additional context**

I have also deleted and readded the driver in backoffice.

Also have tried adding another driver from that same fork `Calendar 2` here https://placeos-dev.aca.im/backoffice/#/systems/sys-GAg-Vlc~-LM/modules which is https://github.com/pkheav/drivers/blob/c56e3e7c5409808498e052163116f4fd8fe5ff30/drivers/place/calendar.cr and results in the same error.
![image](https://user-images.githubusercontent.com/18463731/121181964-7cb85880-c85a-11eb-9112-81ce0098bc35.png)

Not sure if this is the right repo for the issue.

**Comment by stakach** [comment]
I think that means the driver is erroring while loading - before it gets a chance to update redis with its driver list

**Comment by caspiano** [comment]
Is this a backwards compatibility question @pkheav ? Have you tried bringing the fork up to date, or running `shards update`?

**Comment by pkheav** [comment]
thanks @caspiano , yep seems to be a backward compatibility issue. Everything is working fine after running `shards update --ignore-crystal-version` and deleting/recreating drivers from the older fork.
