### ISSUE TITLE
Desk Booking Approval: grant access generates approved_by email

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/drivers#186]
**Describe the bug**

When a user grants access via the concierge UI, the `approved_by` email trigger is fired.

The `approved_by` email trigger should only be fired where a building zone is in manager approval mode and the booking is NOT auto approved.

Secondly when access is granted and the `approved_by` email trigger fires, the booking is also added to the users my day view who granted access.

**To Reproduce**

1. Create a booking.
2. In concierge grant access to the booking by clicking the key icon
3. Second booking confirmation email will be received.

**Expected behaviour**

Where a booking is auto approved i.e. status == approved, the `approved_by` email trigger should not be fired when access is granted.

**Screenshots or a paste of terminal output**

![image](https://user-images.githubusercontent.com/4019090/122846218-b86a1c80-d348-11eb-9d6a-bae9ebc6b8a6.png)

![image](https://user-images.githubusercontent.com/4019090/122846232-bef89400-d348-11eb-8a0f-679e3c37b518.png)

**Comment by stakach** [comment]
> the booking is also added to the users my day view who granted access.
this was a requirement at some point, the frontend can change the query to not show these bookings
