### ISSUE TITLE
DeskBookingLocations and AreaManagement: switch from polling to subscribe/notify

### ISSUE THREAD

**Issue by w-le** [PlaceOS/drivers#245]
Currently DeskBookingLocations and AreaManagement logic only poll the neighboring modules to get new status updates. The default poll rate is every 60s.

So when a frontend app user creates am adhoc desk booking on the map. They would expect that desk to turn red immediately. But it remains green for up to two minutes (depending on how closely the areamgmt poll follows the deskboookinglocations poll).
Many users even think the app is broken when the desk doesn't go red. So they try to create the booking again.

We should all of these logics to a subscribe/notify strategy instead of polling, to ensure that status is updated immediately after a notification from staffAPI or neighboring module.

**Comment by stakach** [comment]
Desk bookings listens for booking changed events and then notifies AreaManagement of a pending update
`area_manager.update_available(matching_zones)`
AreaManagement syncs these out of cycle updates 3 seconds so there is at least some batching going on

Desk bookings sync can also be increased to poll almost as fast as it places a consistent load on staff-api which is not an issue
But if the staff-api redis connection is functioning properly then there should not really be a need to have it polling very quickly - hence the 60 second poll default. although possibly a 15 second poll would be more appropriate
