### ISSUE TITLE
Implement switchable interface on Extron driver

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/drivers#246]
Required for PlaceOS Meet Logic

**Comment by kimburgess** [comment]
Just went to take a look at this. @stakach beat me to it via https://github.com/PlaceOS/drivers/commit/addd5ae47dc8ec585d41e8d2c7173b14fef2f686#diff-a71518107f3a70bc9b544c75c80bdffa8e8e0def85f68c3277f763d3dd82da32.
