### ISSUE TITLE
Floorsense mobile checkin does not handle unknown MAC's

### ISSUE THREAD

**Issue by kimburgess** [PlaceOS/drivers#250]
When a checkin is attempted for an unknown mac address, this is not currently handled gracefully.

https://github.com/PlaceOS/drivers/blob/cf9de15bd5b9068ac996dc732e2e1166a7cda6e7/drivers/floorsense/mobile_checkin_logic.cr#L29-L32

Calls to `eui64_to_desk_id` [may return `nil` as a result](https://github.com/PlaceOS/drivers/blob/cf9de15bd5b9068ac996dc732e2e1166a7cda6e7/drivers/floorsense/custom_bookings_sync.cr#L590-L608). Resulting behaviour is errors similar to the below provided in the response (on development instances that provide error traces), and insufficient logging to correctly indicate cause of the issue:

```
module raised: Expected Hash for #[](key : String), not Nil (Exception)
module raised: Expected Hash for #[](key : String), not Nil (Exception) (PlaceOS::Core::ClientError)
  from app/lib/placeos-core-client/src/placeos-core-client.cr:176:80 in 'execute'
  from app/lib/placeos-core-client/src/placeos-core-client.cr:45:9 in 'exec:security:function:args:request_id'
  from usr/share/crystal/src/log/log.cr:36:3 in '???'
  from usr/share/crystal/src/primitives.cr:266:3 in 'call'
  from usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from usr/share/crystal/src/http/server/request_processor.cr:51:11 in 'process'
  from usr/share/crystal/src/http/server.cr:500:5 in '->'
  from usr/share/crystal/src/primitives.cr:266:3 in 'run'
  from ???
```

**Comment by stakach** [comment]
error improved in 6c23a0a5faccf77830ff6d74cfb024c06763d0be
