### ISSUE TITLE
SenseStudio Occupancy Driver

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/drivers#295]
Develop SenseStudio Occupancy Sensor Driver, functionality is similar to Vergesense where a named area is created then data is pushed to PlaceOS.

Full API Documentation: https://drive.google.com/drive/folders/1ytXYPMyt1e6YrpV3ovyclUBrU8v6eP5v

**Comment by w-le** [comment]
A similar product is Vergesense, for which we already have existing drivers that can be used for reference when developing this new SenseStudio driver:
https://github.com/PlaceOS/drivers/tree/master/drivers/vergesense
https://vergesense.readme.io/reference/reference-getting-started
