### ISSUE TITLE
New Driver: Crestron Fusion API (HTTPS/JSON)

### ISSUE THREAD

**Issue by w-le** [PlaceOS/drivers#310]
**Driver Type**

Service 

**Manufacturer**

Crestron

**Model/Service**

Fusion REST API

**Link to or Attach Device API or Protocol**

https://www.crestron.com/getmedia/441932cf-e0c9-4e3a-89f6-2659b3162832/mg_gs_intro_crestron_fusion_software_api 

Security related info (documents says pertaining to cloud, Crestron says also applies to on prem fusion server etc)
https://www.crestron.com/getmedia/6e98a738-89d9-4262-bc16-bd9e2ba7cdb5/mg_crestron_fusion_cloud_service_security_guide_1 

[Crestron Fusion Software API: Developer Microsite](https://sdkcon78221.crestron.com/sdk/Fusion_APIs/Content/Topics/Home.htm)

[Crestron Fusion API](https://sdkcon78221.crestron.com/sdk/Fusion_APIs/Content/Topics/Default.htm)

[Crestron Fusion API Development Resources](https://help.crestron.com/fusion/Content/Topics/Configuration/Crestron-Fusion-API-Development-Resources.htm)

https://drive.google.com/drive/folders/1BfI3vgjBk2FM64ZZjiRAgb2K5uHs8PsF?usp=sharing

If any additional docs are required, just as me and we can request them.

**Describe any desired functionality**

- Execute functions on given Crestron controllers (e.g. execute startup or shutdown on a specific room)

**Additional context**

For a university project starting now

**Comment by chillfox** [comment]
[Crestron_API.zip](https://drive.google.com/file/d/1b31WxQwpm3Qgn9YxvhHHxnOqc9wo_NVP/view)
[Crestron_Fusion_API.zip](https://drive.google.com/file/d/1RzaGEuMqqCeCEebULv1QtQ_PRmxXKkYb/view)
