### ISSUE TITLE
Bug: DNA Spaces Error on Incorrect JWT

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/drivers#321]
**Describe the bug**

If the JWT (activation token) is incorrect, DNA Spaces driver will fail to authenticate. The error is not displayed in backoffice when activating and must be obtained from core logs.

**To Reproduce**

Attempt to authenticate DNA Spaces driver with incorrect activation token.

**Expected behaviour**

Driver should error reporting the JWT was incorrect.

**Screenshots or a paste of terminal output**

![image.png](https://images.zenhubusercontent.com/5f7efb49f50062d6404b6473/d53c5141-6be1-4800-91c3-1f25a10f8ec5)

**Comment by w-le** [comment]
same as https://github.com/PlaceOS/drivers/issues/367
