### ISSUE TITLE
Siemens Desigo Driver

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/drivers#339]
https://drive.google.com/file/d/1ZxrVWLCF3iKaM-eC4vPk8YJlndb882aj/view?usp=drivesdk

**Comment by w-le** [comment]
fyi @jeremyw24 I've assigned this to @grkek as he's finished with Axiom and we are temporarily blocked on e2e testing Infosilem. So this one can be started based on the API docs. 
API access is coming shortly but we should make a start based on the docs first.
