### ISSUE TITLE
Issue with driver to detect People Count 

### ISSUE THREAD

**Issue by ksra08** [PlaceOS/drivers#384]
Sensor count set to a room once is not retained. To reproduce:
- Set the sensor count to 10 and execute the command for room 6-09.
- Worked initially for one event
- Switched to another system in building zone in backoffice 
- Created another event for room 6-09 
- For system 6-09 on checking the debug logs, people count was shown as 0 
<img width="768" alt="Screen Shot 2022-11-09 at 5 56 01 pm" src="https://user-images.githubusercontent.com/78706760/200761146-d2e9bf0a-cc9d-4ee0-a88a-734627c75074.png">

**Comment by w-le** [comment]
Thanks sravani,
Can you help grab the js console logs from backoffice (Log level debug, error and info) while the debug checkbox of the Eventattendancerecorder and Staff API modules in that room are selected, at the moment that the event ends?

This is the moment that eventattendancerecorder  module will tell staff-api module to execute patcheventmetadata to store the people count for that event. The key to solving this issue will the be the outcome of that patcheventmetadata (Or confirming that it did not occur at all for some buggy reason). In an initial test in that same system I did confirm that the patcheventmetadata succeeded.

**Comment by ksra08** [comment]
Sure I've created another event now to monitor the logs. I'll share them once event ends

**Comment by w-le** [comment]
thanks for troubleshooting @ksra08 , steve has made a fix and i've deployed the updated driver to the cluster we were testing on. Do let us know if that has resolved the issue, thanks.

https://github.com/PlaceOS/drivers/commit/86454d819a226e3680972cae7677108ec93ed451

**Comment by ksra08** [comment]
@stakach  Noticing 0 counts again for few events today. It might have occurred after these back to back meetings in the screenshot below got ended. The last 3 meetings below returned 0  all the previous events worked fine. 
<img width="543" alt="Screen Shot 2022-11-17 at 2 58 19 pm" src="https://user-images.githubusercontent.com/78706760/202351916-32b0847b-3a83-4499-9c86-36109ee5621f.png">
<img width="1677" alt="Screen Shot 2022-11-17 at 3 02 19 pm" src="https://user-images.githubusercontent.com/78706760/202352189-7c4e6ed8-7c7c-4dfe-b533-60543e7a19ae.png">

**Comment by stakach** [comment]
the issue here is stale data
![image](https://user-images.githubusercontent.com/368013/202355432-2fa5cf46-9c22-4b5d-a52d-a484325e51b0.png)

as I was using this to test room booking cancellation, so just need to update it periodically even if it's to the same count
