### ISSUE TITLE
Driver Request: Qbic Touch Panel Driver

### ISSUE THREAD

**Issue by jeremy-west** [PlaceOS/drivers#52]
**Driver Type**

Device

**Manufacturer**

Qbic

**Model/Service**

TD-1060

**Link to or Attach Device API or Protocol**

https://drive.google.com/drive/folders/1DJhuAo1XoOGjfD-K1Pbey_SL1-e8emaY

**Describe any desired functionality**

- Set Content URL
- Get Device Status
- Set Reboot Schedule
- Perform Adhoc Reboot

**Comment by pkheav** [comment]
Okay got the content setting method working properly on pwc me https://pwcme.dev.place.tech/backoffice/#/systems/sys-Fm46y~SsO52/modules and the latest file here https://github.com/pkheav/drivers/blob/master/drivers/qbic/touch_panel.cr
