### ISSUE TITLE
Driver Request: Vergesense

### ISSUE THREAD

**Issue by w-le** [PlaceOS/drivers#70]
**Driver Type**

Device (cloud service)

**Manufacturer**

Vergesense

**Model/Service**

Vergesense API (cloud)

**Link to or Attach Device API or Protocol**

https://vergesense.readme.io/reference

**Describe any desired functionality**

Similar to [Meraki Scanning+Dashboard API driver](https://github.com/PlaceOS/drivers/blob/master/drivers/cisco/meraki/dashboard.cr), in that 
1. a Trigger will be configured to receive Vergesense webhooks
2. the driver will also be able to HTTPS GET data from vergesense REST API

- Authenticate
- Subscribe to Webhooks
- Query /buildings / spaces /sensors
- Expose status of each building/space/sensor
- In the near future, the module state will be streamed to a time series DB via MQTT using [placeos/source](https://github.com/PlaceOS/source) . Ensure the status is stored in a way that suits this MQTT state streaming and retrospective analysis

**Additional context**

The driver will be used to offer:
- real time red/green (occupied) status of desks on maps
- confirming whether a desk gets occupied or not at the time of it's booking
- real time headcount of people in spaces, affecting highlight colour of that area in maps

**Comment by jeremyw24** [comment]
Redant to do primary development.
