### ISSUE TITLE
XY Sense

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/drivers#77]
**Driver Type**

Device

**Manufacturer**

XY Sense

**Model/Service**

https://www.xysense.io/technology

**Link to or Attach Device API or Protocol**

https://drive.google.com/drive/folders/16ySW7tJnVQgIMuP-wqIYRQYejCkU6xKQ

**Describe any desired functionality**

- Control all aspects of device
- People Count

**Comment by jeremyw24** [comment]
XY Sense App Portal: https://app.xysense.io/
Creds in BitWarden as XY Sense Portal

**Comment by stakach** [comment]
this is located in our NDA drivers as the protocol is under NDA https://github.com/place-labs/nda-drivers
the location services adaptor is in this repo
