### ISSUE TITLE
Driver Request: Lenel OpenAccess

### ISSUE THREAD

**Issue by kimburgess** [PlaceOS/drivers#86]
**Manufacturer**

Lenel

**Model/Service**

OpenAccess

**Link to or Attach Device API or Protocol**

http://www.lenel.com/assets/images/solutions/open-integration/OpenAccessUserGuide.pdf

**Describe any desired functionality**

- visitor management
- mobile card allocation

**Comment by KimBurgess** [comment]
Blocked. See https://github.com/PlaceOS/drivers/pull/24#issuecomment-736525336
