### ISSUE TITLE
Bug: Samsung MCD driver checksum calculation is incorrect

### ISSUE THREAD

**Issue by PhilPearson** [PlaceOS/drivers#87]
**Describe the bug**
The way the checksum is being calculated in the Samsung MDC driver is incorrect as are the return values in the tests.

**To Reproduce**
The correct response to a power query (where the power is ON) is `responds("\xAA\xFF#{id}\x03\x41\xF9\x00\x3c")`

When running the test with the correct return value the module will log an error `"Invalid checksum, checksum should be: ff"`

**Comment by pkheav** [comment]
Thanks for picking this up @PhilPearson
