### ISSUE TITLE
Pinger driver logging errors

### ISSUE THREAD

**Issue by PhilPearson** [PlaceOS/drivers#91]
**Describe the bug**

Whilst the pinger module works correctly it generates an error each time it calls the `ping` function

```
8:52 AM, Ping_1, [INFO] connecting to device
Error connecting to 'device-under-test.testdevices.com.au:9': Connection refused (Socket::ConnectError)
  from ../usr/share/crystal/src/socket/addrinfo.cr:73:15 in 'initialize'
  from ../usr/share/crystal/src/socket/tcp_socket.cr:27:3 in 'initialize:connect_timeout'
  from ../usr/share/crystal/src/socket/tcp_socket.cr:27:3 in 'new:connect_timeout'
  from repositories/drivers/lib/placeos-driver/src/placeos-driver/transport/tcp.cr:43:24 in 'start_socket'
  from repositories/drivers/lib/placeos-driver/src/placeos-driver/transport/tcp.cr:37:9 in 'connect'
  from repositories/drivers/lib/placeos-driver/src/placeos-driver/driver_manager.cr:93:34 in '->'
  from ../usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from ../usr/share/crystal/src/fiber.cr:92:34 in '->'
  from ???
```

**To Reproduce**

1. Create a new driver using the pinger module (type device)
2. Add new module to system using the pinger module and give it an ip address (or fqdn) leaving all other settings default
3. Start and exec the ping function
4. Ping results connected true (as expected)
5. Whilst at the same time generating a connection error

**Expected behaviour**

When a ping result returns true it should not also generate an error in the log file to do with connection errors

**Comment by caspiano** [comment]
Will take a look at this today, thanks for the report!

**Comment by PhilPearson** [comment]
I've not had the chance to confirm, but I suspect that this could be due to not checking the UDP option.

**Comment by stakach** [comment]
yes, should be configured as UDP - I think backoffice should be selecting this by default
